version: "3.5"

networks:
    codeshare:
        external: false

services:
    server:
        build: .
        container_name: codeshare_server
        networks:
            - codeshare
        volumes:
            - /var/codeshare:/data
        ports:
            - "${HTTP_PORT}:80"
        environment:
            - HTTP_PORT=${HTTP_PORT}
            - BASE_URL=${BASE_URL}
            - ADMIN_TOKEN=${ADMIN_TOKEN}
            - DATABASE_URL=${DATABASE_URL}
            - API_KEY=${API_KEY}
            - AUTH_DOMAIN=${AUTH_DOMAIN}
            - PROJECT_ID=${PROJECT_ID}
            - STORAGE_BUCKET=${STORAGE_BUCKET}
            - MESSAGE_SENDER_ID=${MESSAGE_SENDER_ID}
            - APP_ID=${APP_ID}
            - MEASUREMENT_ID=${MEASUREMENT_ID}
